# You can find your API token at https://toggl.com/app/profile
TogglAPIToken = ""
HoursPerDay = 8
# RollbarToken = ""
# RollbarEnv = ""

Port = 3000
Debug = false
TemplatesGlobPattern = "./templates/*.tmpl"